spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: utf-8

server:
  port: 8888
